services:
    _defaults:
        autoconfigure: true

    contao.install_tool:
        class: Contao\InstallationBundle\InstallTool
        arguments:
            - '@database_connection'
            - '%kernel.project_dir%'
            - '@logger'
            - '@Contao\CoreBundle\Migration\MigrationCollection'
        public: true

    contao.install_tool_twig_extension:
        class: SensioLabs\AnsiConverter\Bridge\Twig\AnsiExtension

    contao.install_tool_user:
        class: Contao\InstallationBundle\InstallToolUser
        arguments:
            - '@session'
        public: true

    contao.installer:
        class: Contao\InstallationBundle\Database\Installer
        arguments:
            - '@database_connection'
            - '@Contao\CoreBundle\Doctrine\Schema\SchemaProvider'
        public: true
